### ISSUE TITLE
Having trouble with wifibox w/ Intel AX200

### ISSUE THREAD

**Issue by EnokiPPT** [pgj/freebsd-wifibox#10]
Hey there,
I'm new to FreeBSD and have been wanting to switch for a while, but the bad wifi support had always turned me off. Then I found out that wifibox existed so I switched to try it. However, I'm having some trouble getting it to work. After following the instructions on the man page, using it to ping any address results in a very long pause and then "ping: unknown host". Pinging 8.8.8.8 results in 100% packet loss with "Destination host unreachable".
What can I do?

ifconfig:
![IMG_20220115_113902~2](https://user-images.githubusercontent.com/52358711/149633917-da631647-607e-4284-8f19-abf55ae2a295.jpg)

**Comment by EnokiPPT** [comment]
Running `wifibox console` also results in
`ERROR: No null-modem device is configured`

**Comment by pgj** [comment]
I think the problem might be that the BHyVe PCI pass-through does not work well with Intel AX200 chipsets unless a recent version of `13-STABLE` or `14-CURRENT` is used where this has been fixed.  Could you please try with those versions?

Regarding the `console`, it must be first enabled in the `bhyve.conf` configuration file.  But it is not required for exploring the contents of the `dmesg`: it is available on the host system under `/var/run/wifibox/appliance/log/`.

**Comment by pgj** [comment]
Also, be aware of https://github.com/pgj/freebsd-wifibox-image/issues/1.

**Comment by EnokiPPT** [comment]
@pgj 
Hello, I'm using the latest version of 13-STABLE so that shouldn't be the issue. I'm trying to login to the console but I don't know what the password for login is supposed to be and there is no info in /usr/local/etc/wifibox.

**Comment by EnokiPPT** [comment]
Additionally, during power on the bhyve vm shows that it fails to acquire a DHCP lease. Could this be because of the file I need to rename?

**Comment by pgj** [comment]
> @pgj Hello, I'm using the latest version of 13-STABLE so that shouldn't be the issue. I'm trying to login to the console but I don't know what the password for login is supposed to be and there is no info in /usr/local/etc/wifibox.

You can use the `root` user to login and there is no password (by default).

**Comment by pgj** [comment]
> Additionally, during power on the bhyve vm shows that it fails to acquire a DHCP lease. Could this be because of the file I need to rename?

Messages in `dmesg` can tell you all I believe: check if the `iwlwifi` driver was able to initialize.  You should see something like this:

```console
$ fgrep iwlwifi /var/run/wifibox/appliance/log/dmesg
[    2.274947] iwlwifi 0000:00:06.0: can't derive routing for PCI INT A
[    2.274950] iwlwifi 0000:00:06.0: PCI INT A: not connected
[    2.287020] iwlwifi 0000:00:06.0: loaded firmware version 36.ca7b901d.0 8000C-36.ucode op_mode iwlmvm
[    2.402954] iwlwifi 0000:00:06.0: Detected Intel(R) Dual Band Wireless AC 8260, REV=0x204
[    2.501365] iwlwifi 0000:00:06.0: base HW address: 7c:76:35:99:03:cc
```

If the driver fails to initialize, then yes, you might need to follow the advice in the issue I cited above.  (I do not have an Intel AX200 card, you cannot verify this myself.)

**Comment by EnokiPPT** [comment]
Can't believe I didn't try that. Logged in, renamed the file, but running `rc-service networking restart` still says that wlan0 failed to get a DHCP lease.

**Comment by EnokiPPT** [comment]
Driver is failing to initialize. See picture
![IMG_20220115_143449](https://user-images.githubusercontent.com/52358711/149638425-0aff530f-5473-424a-b7ba-9ac6fefb3603.jpg)

**Comment by pgj** [comment]
> Driver is failing to initialize.
I am not entirely sure of that: it gets an HW address at the end, which is a good sign, I think.  What does `/var/run/wifibox/appliance/log/messages` say?  Could `wpa_supplicant` start up?  Do you have a working `wpa_supplicant.conf`?

**Comment by EnokiPPT** [comment]
What would a competent `wpa_supplicant.conf` look like? I have no idea where to start writing one to work with this.

**Comment by pgj** [comment]
The `wpa_supplicant.conf(5)` man page can help you with understanding that.  But in essence, it is something like this:

```console
network={
  ssid="<wifi network>"
  psk="<wifi network password>"
  key_mgmt=WPA-PSK
}
```

Place this under `/usr/local/etc/wifibox/wpa_supplicant.conf`.

**Comment by EnokiPPT** [comment]
Looks to be working! I'll get a window manager going and let you know if it works. Thanks for the help, I thought wpa_supplicant.conf would need to be different for some reason.

**Comment by pgj** [comment]
I am glad that it works now.  Let me know if I could close the issue.

**Comment by EnokiPPT** [comment]
Update: It works! My wifi is pretty bad so now I can use freebsd without horrifyingly slow wifi.
Again, thanks a bunch for the help!
![Uploading IMG_20220115_164610.jpg…]()
