### ISSUE TITLE
Please consider clarifying that wifibox has it's own wpa_supplicant.conf

### ISSUE THREAD

**Issue by nospam2998** [pgj/freebsd-wifibox#103]
### Description

Currently wifibox-alpine(5) reads:

> For the ease of management, the host shares configuration files …

…

> The wpa_supplicant/wpa_supplicant.conf or hostapd/hostapd.conf
> configuration file is shared with the host through the
> /etc/wpa_supplicant or the /etc/hostapd directory respectively, where the
> app_config 9P (VirtFS) share is mounted. …

while fully correct and complete. I was misreading the above to believe that wifibox actually shared its configuration with `/etc/wpa_supplicant.conf` of the host system. It might be worth clarifying slightly as:

```
From 9dbee1b74a59ead6d88a8fb1c2a69857a7ddd997 Mon Sep 17 00:00:00 2001
From: cos <cos>
Date: Thu, 23 May 2024 10:02:24 +0200
Subject: [PATCH] man: Clarify that wifibox have its own config files

---
 man/wifibox-alpine.5 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/man/wifibox-alpine.5 b/man/wifibox-alpine.5
index 0c5300a..1f2cb22 100644
--- a/man/wifibox-alpine.5
+++ b/man/wifibox-alpine.5
@@ -337,7 +337,7 @@ is used directly from this location by
 .Sy uds_passthru .
 .El
 .Pp
-The
+The wifibox instance of
 .Pa wpa_supplicant/wpa_supplicant.conf
 or
 .Pa hostapd/hostapd.conf
-- 
2.43.0
```

Yet I can definitely see the argument against adding words to an already correct text. Please feel free to patch or reject this issue as you see fit.

### Host operating system

```shell
N/A
```

### Wireless NIC

```shell
N/A
```

### Wifibox version

```shell
Current main (3ce5b1f) of freebsd-wifibox-alpine.
```

### Disk image type and version

N/A

### Changes to the default configuration files

```shell
N/A
```

### Logs

```shell
N/A
```

### Additional context

N/A

### Have you tried to turn it on and off?

- [X] Yes, I have read all the manual pages first!

**Comment by pgj** [comment]
Thanks for the suggestion!  I can see the reasons why you or others may find this part of the manual page confusing.

Note that the manual page discusses the internals of the guest image to facilitate troubleshooting mainly, but it can serve as a technical documentation.  At the description of tools, it is mentioned for both `wpa_supplicant` and `hostapd` that they use the Linux version of the configuration files.  The discussion then continues with the location of the files and the places where they are mounted on the guest.

But for example, the "root" of either the `appliance` or the `wpa_supplicant` / `hostapd` is not made clear so something along the lines of your proposed change could make sense.  I will have to think about this a little bit -- I will get back to you about this with a PR sometime soon.

**Comment by pgj** [comment]
@nospam2998 please check https://github.com/pgj/freebsd-wifibox-alpine/pull/24 to see if that answers your concerns.
