### ISSUE TITLE
destroy_nmdm function in wifibox does the opposite of what is expected

### ISSUE THREAD

**Issue by MegaManSec** [pgj/freebsd-wifibox#104]
### Description

The [destroy_nmdm function in sbin/wifibox](https://github.com/pgj/freebsd-wifibox/blob/4810e255edd4286658662538ec7ce5c9b371eef4/sbin/wifibox#L305) does the opposite of what it is intended to do.

An nmdm device is created upon any access to /dev/nmdm.. -- this includes by `test -c` and even `rm`. When `destroy_nmdm` is run, it effectively: created the /dev/nmdm devices, removes the entries from /dev/, and believes the device is destroyed. This behavior can be seen by showing that removing any /dev/nmdm.. always "succeeds", because the device is created and is immidetly removed:

```
user@evilco:~$ ls /dev/nmdm*
user@evilco:~$ sudo rm /dev/nmdmUA # created and deleted2
user@evilco:~$ sudo rm /dev/doesnotexist
rm: /dev/doesnotexist: No such file or directory
```

However, removing the device from /dev/ does not destroy the device. Although the existence of the device is opaque to the filesystem, it still exists: in a state which cannot easily be destroyed now that its file in the devfs has been deleted. This means that the kernel module cannot be unloaded either, since the device still exists.

At the moment, it is not possible to start wifibox, stop wifibox, and then unload the `nmdm` kernel module. It fails because the ghost device is created by the `destroy_nmdm` function (fixed in https://github.com/freebsd/freebsd-src/pull/1367). A similar example:

```
user@evilco:~$ sudo kldload nmdm
user@evilco:~$ sudo kldunload nmdm
user@evilco:~$ sudo kldload nmdm
user@evilco:~$ [ -e /dev/nmdmAA ] && echo exists
user@evilco:~$ sudo kldunload nmdm
kldunload: can't unload file: Device busy
```

---

I propose removing the destroy_nmdm function completely. When the VM is destroyed, it already closes the nmdm device.

**Comment by pgj** [comment]
Thanks for reporting this issue!  Yes, I agree that is a good proposal.  Looks like I did not notice that `nmdm(4)` works like this.  Please give me some time to come up with a fix.

**Comment by pgj** [comment]
I proposed a fix in #105 that you can test by using the `chore/net/wifibox-core/remove-nmdm-device-management` branch of the `pgj/freebsd-wifibox-port` repository:

https://github.com/pgj/freebsd-wifibox-port/tree/chore/net/wifibox-core/remove-nmdm-device-management

This is going to install version `0.14.0` of `net/wifibox`.  I have been running this in the last few days and it is working, but let me know about your feedback.

**Comment by MegaManSec** [comment]
I will test it out today.

**Comment by pgj** [comment]
@MegaManSec I have not heard back from you.  Under [lazy consensus](https://medlabboulder.gitlab.io/democraticmediums/mediums/lazy_consensus/), I assume you do not have any objections against merging it?  I still have not noticed any issues.

**Comment by MegaManSec** [comment]
Yes LGTM
