### ISSUE TITLE
Is there possibility to create AP?

### ISSUE THREAD

**Issue by iron-udjin** [pgj/freebsd-wifibox#22]
Hello,

It would be great to have possibility to start wifibox in AP mode to have possibility share internet connection or LAN resources between connected clients.

I have in wpa_supplicant.conf:
```
ctrl_interface=/var/run/wpa_supplicant
ctrl_interface_group=0
update_config=1

network={
    ssid="test-ap"
    mode=2
    key_mgmt=WPA-PSK
    psk="test"
    frequency=2462
}
```
My clients see AP and successfully connect to it. But I have no idea how to configure DHCP server and iptables NAT rules there. It would be great to have mention regarding AP in documentation or even sample configs.

Thank you!

**Comment by pgj** [comment]
Hi @iron-udjin, thanks for nudging me about this.  Wifibox was not created with AP mode in mind, but I also agree that this is possible.  The [Alpine-based guest](https://github.com/pgj/freebsd-wifibox-alpine) uses the DHCP server shipped with [BusyBox](https://busybox.net/), called [`udhcpd`](https://udhcp.busybox.net/).  Its configuration is available at `$ETCDIR/wifibox/udhcpd.conf`.  (However, it may happen another file would be needed for the `wlan0` interface...)

Unfortunately, the `iptables` NAT rules are not exposed but packed inside the disk image currently -- but this could be easily changed.  If you are using the 0.8.x series with [the older disk image format](https://github.com/pgj/freebsd-wifibox-image/), you can just enter the guest via the console and change the NAT rules to your needs, see the `wifibox-alpine(5)` man page.  For the newer, SquashFS-based format, it is a bit more trickier as the [customized `iptables` package](https://github.com/pgj/freebsd-wifibox-alpine/tree/main/aports/iptables) and the whole image [have to be rebuilt](https://github.com/pgj/freebsd-wifibox-port/blob/main/net/wifibox-alpine/Makefile) with the updated config.

Or you can wait until I get there to put together something for testing.  I will share here if there is any specific progress on the subject.

**Comment by pgj** [comment]
I created a modified version of the guest image that you can install by the updated version of the [`net/wifibox-alpine` port](https://github.com/pgj/freebsd-wifibox-port/tree/0dbe0f743591be2e18fae0ead1c2305aad9cf8b7).  Then it becomes possible to make Wifibox work in AP mode too!

Besides the changes to `wpa_supplicant.conf` you mentioned in the description, files with contents along these are needed under `$ETCDIR/wifibox`.

`interfaces.conf`:

```
iface eth0 inet static
  gateway 10.0.0.1
  address 10.0.0.100/24

iface wlan0 inet static
  address 192.168.0.1/24
```

`iptables`:

```
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
[0:0] -A FORWARD -i wlan0 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT
[0:0] -A FORWARD -i wlan0 -o eth0 -j ACCEPT
COMMIT
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
[0:0] -A POSTROUTING -o eth0 -j MASQUERADE
COMMIT
```

`udhcpd.conf`:

```
start           192.168.0.2
end             192.168.0.254
max_leases      64
interface       wlan0
opt     subnet  255.255.255.0
opt     router  192.168.0.1
opt     dns     8.8.8.8 8.8.4.4
opt     lease   864000
```

In addition to this, the `wifibox0` interface should have the `10.0.0.1/24` address (which is the gateway for the guest) and be connected to the interface facing towards the Internet.  In my case, that was `em0` and I used `pf(4)` to do the NAT for it in `/etc/pf.conf`:

```
scrub all
nat on em0 from 10.0.0.0/24 to any -> em0
pass log all
```

Remember to enable IP forwarding on the host, in `/etc/sysctl.conf`:

```
net.inet.ip.forwarding=1
``` 

Let me know if this works.

**Comment by iron-udjin** [comment]
Works! Thank you! But... AP works only in 802.11n mode. Can you please add `hostapd` in the guest image with possibility to edit `hostapd.conf` in `$ETCDIR/wifibox`?

Is there way to assign `10.0.0.1/24` when `wifibox0` becomes up?

**Comment by pgj** [comment]
Yes, I have been also thinking about adding support for `hostapd`.  But, to keep the image hardened, I want to make it a configuration option for the port, so thatthe user could choose between using `wpa_supplicant` (client mode) and `hostapd` (AP mode).  This requires some further code changes, therefore it needs some more time.

The automated assignment of the IP address for `wifibox0` can be configured in `/etc/rc.conf`, for example:

```
ifconfig_wifibox0="inet 10.0.0.1/24"
```

**Comment by pgj** [comment]
I have implemented the support for hosting `hostapd` in Wifibox and published it in https://github.com/pgj/freebsd-wifibox-port/tree/f319b641eefb2b4c2f77fdf6679f83bba6aa5f5d -- you can test it, if you want.

**Comment by pgj** [comment]
@iron-udjin have you had the chance to try the `hostapd` Wifibox integration?

**Comment by iron-udjin** [comment]
@pgj Sorry for delay. The war in going in my country. Currently I don't have possibility to test it. I'll let you know when I'll have time/possibility to setup and test everything.

**Comment by pgj** [comment]
Okay.

**Comment by thesunexpress** [comment]
> @pgj Sorry for delay. The war in going in my country. Currently I don't have possibility to test it. I'll let you know when I'll have time/possibility to setup and test everything.

Damn it. Putler's black hand even reaching & screwing with our lives here in `wifibox` community. All the more reason to support a swift end to the atrocities. 

Starting to test HostAP now.

**Comment by thesunexpress** [comment]
FYI: 48 hours running networking stress test with `wifibox` = zero issues.
I shall be doing the same with HostAP features soon.

**Comment by pgj** [comment]
The implementation for supporting this feature is done and it will be part of the next release.  Therefore I am closing this ticket.  Please open another issue if you find any problems.
