### ISSUE TITLE
Anyway to make listening ports working (like sshd)?

### ISSUE THREAD

**Issue by Alix82** [pgj/freebsd-wifibox#35]
ssh'ing to my machine while it has only wifibox network running results in connection refused from the client. It obviously works when using if_iwm of other "direct" network interfaces.

Any incoming packets on port 22 are answered by RST by the Linux VM. I couldn't figure out how to forward incoming packets using wifibox's configuration

**Comment by pgj** [comment]
Yes, that is possible, please refer to the comments in #18.

**Comment by Alix82** [comment]
Sorry for the noise, I didn't pay attention that wifibox already provides console access to the VM. 

I've used the following rule to get ssh access from, and to the box where wifibox is running.

iptables -t nat -A PREROUTING -p tcp --dport 22 -j DNAT --to-destination 10.0.0.2:22 ! -s 10.0.0.2

please feel free to close this.

**Comment by pgj** [comment]
No problem, this is kind of a hidden "feature" and it is not properly advertised.  As I promised in #18, it would like to make it a bit more easier to use and more visible for the users.

**Comment by pgj** [comment]
This is going to be solved as part of #18.
