### ISSUE TITLE
Default routing issue

### ISSUE THREAD

**Issue by mkohanim** [pgj/freebsd-wifibox#37]
Hi Gábor,

In the case where the WiFi network is already at 10.0.0.x, configuring wifibox0 to 10.0.0.1 or 3 or using udhcpd to assign a range from 10.0.0x range may cause IP conflict with IPs already assigned by the host AP/router. Are there any automated mechanisms to detect and correct the IP for wifibox and eth0?
Thank you.

**Comment by pgj** [comment]
There is no automation in place to detect the conflicting settings.  One can always change the related settings by modifying the `interfaces.conf` and `udhcpd.conf` files under `$ETCDIR/wifibox/appliance` -- or generate it automatically by some other tool that can consider other previously configured networks.

**Comment by mkohanim** [comment]
Hi Gábor, thank you. This is going to be rather difficult because the script has to run on the vm to detect network and then update the interfaces.conf and restart itself. In order for anything to run in the VM, well, it has to be part of the wifibox package. I don’t mind working on this as long as there’s a way to include it in wifibox.

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by pgj** [comment]
Oh, in that case the pre-generated configuration files will not help indeed.  Creating a patch to implement this functionality is a great idea, I am more than happy to review it.  This would also give a better insight what the details are and how it could be solved properly.

**Comment by mkohanim** [comment]
Hi Gábor,

Much more difficult than I had expected. Due to the shortage of time, I have opted to use a very random IP in the 172.16. range with subnet of 255.255.255.0. Seems to work very well with a variety of routers. 

Did you ever succeed in getting DHCP DNS through?

Thank you.

**Comment by pgj** [comment]
There is currently an on-going discussion about forwarding DNS information through DHCP in #30, if that is what you meant.

**Comment by mkohanim** [comment]
Yes, thank you.

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by mkohanim** [comment]
Gábor, is there any way to get the guest IP from host? Also, you can close this issue. Everything else is working fantastically …

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

From: Michel Kohanim
Sent: Monday, September 12, 2022 8:27 AM
To: pgj/freebsd-wifibox ***@***.***>; pgj/freebsd-wifibox ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [pgj/freebsd-wifibox] Default routing issue (Issue #37)

Yes, thank you.

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by pgj** [comment]
@mkohanim do you mean the IP address that the guest gets on connecting to the wireless network, i.e. the address assigned to `wlan0` there?  WPA Supplicant clients, e.g. `wpa_cli` can be used to query this kind of information.  For example:

~~~
wpa_cli status | fgrep ip_address | sed 's|.*=||'
~~~

But WPA Supplicant implements [its own protocol](https://w1.fi/wpa_supplicant/devel/ctrl_iface_page.html) over the corresponding UNIX domain socket (e.g. `/var/run/wpa_supplicant/wlan0`, with which one can communicate directly.  Note that this is available if the control socket interface is enabled in WPA Supplicant's configuration file.  For example, this is a way to query the status without `wpa_cli` but using `nc` (netcat):

~~~
echo STATUS | nc -w 1 -uU /var/run/wpa_supplicant/wlan0 | fgrep ip_address | sed 's|.*=||'
~~~

**Comment by mkohanim** [comment]
Hi Gabor, yes, but I want to get to this information from the host (wpa_supplicant is running in the the guest).


With kind regards,



******************************

  Michel Kohanim

             CEO



  (p) 818.631.0333

  http://www.universal-devices.com<http://www.universal-devices.com/>

******************************

________________________________

**Comment by pgj** [comment]
@mkohanim even if `wpa_supplicant` is running in the guest, it is possible to talk to it on the host.  Wifibox has a feature called "Unix domain socket passthrough" that mirrors the control sockets (e.g. `/var/run/wpa_supplicant/wlan0`) on the host and they can be addressed as if they are local ones.  There is no `wpa_cli` or such installed in the guest, I was running it from the host in the examples above.

**Comment by mkohanim** [comment]
Gábor, fantastic, thank you so much!

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by pgj** [comment]
I am happy to help (if time permits).  Per your previous request, I am closing the ticket now.
