### ISSUE TITLE
mDNS and other multicast UDP packets 

### ISSUE THREAD

**Issue by mkohanim** [pgj/freebsd-wifibox#40]
Hi Gábor,

Any idea how we can pass through mDNS or other multicast packets (such as UPnP)? Currently, all TCP and direct UDP packets work fine but no UDP multi/broadcast packets work.

Thank you.

**Comment by pgj** [comment]
It should just be matter of the `iptables` tables in use, I believe.  I have not tried any of these personally, though.

**Comment by mkohanim** [comment]
Thank you Gábor. I have been looking but a little outside of my expertise. Basically, I need to forward the following from wlan0 to eth0:
src: any
dest: 224.0.0.251
protocol: udp
dest port: 5353

**Comment by pgj** [comment]
I have just learned that mDNS and NAT do not go well together.  But there are projects like [mdns-repeater](https://github.com/geekman/mdns-repeater/) to provide a workaround.

**Comment by mkohanim** [comment]
This is precisely what I need! How do I get it installed on the guest?

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by pgj** [comment]
You will have to create an Alpine Linux package and have it installed during the build.  Or use a different VM image with your favorite Linux flavor where you can just compile the code and run it.

**Comment by pgj** [comment]
For testing, you can also compile the code (statically) somewhere else and copy to the guest over one of the shared (VirtFS) folders.  Then use the `console` command to enter the guest and run the application.

**Comment by mkohanim** [comment]
Thank you Gábor. I just do not have the expertise and resources.

With kind regards,

******************************
  Michel Kohanim
             CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by pgj** [comment]
This has been included in the guest image in https://github.com/pgj/freebsd-wifibox-port/commit/71ebb910c20c65e03caf7489ae8484c485aa07c4 hence closing this ticket.
