### ISSUE TITLE
wpa[23]-enterprise

### ISSUE THREAD

**Issue by ish-org** [pgj/freebsd-wifibox#46]
I tested wifibox on FreeBSD 14-Current with intel AX210ngw wifi card.
It works fine wpa2-personal but seems that wpa2-enterprise is not working.
Is there any way to use wpa2-enterprise ?

**Comment by pgj** [comment]
Hi @ish-org, could you please be more specific?  How did you try to configure WPA Enterprise and what did you get?

**Comment by ish-org** [comment]
Sorry, this is a bug of wpa_supplicant 2.10.
My wifi router(buffalo WAPM-APG600H) is too old and internal radius didn't support TLS 1.2 and uses SSL3.
Although this bug was fixed at wap_supplicant 2.10.7, it seems that the latest wpa_supplicant for alpine is wpa_supplicant-2.10-r4.apk.  So, I made back to wpa_supplicant-2.9-r17 (and libssl1.1-1.1.1t-r1 and libcrypto1.1-1.1.1t-r1), it worked well.
Another solution is to use external radius server. I installed freeradius on FreeBSD 13.1-R server and this works fine with  wpa_supplicant-2.10-r1.apk.

**Comment by pgj** [comment]
Thank you very much for tracking down this issue!  Although Alpine Linux indeed includes only `wpa_supplicant` 2.10 (even on `edge`), Wifibox can independently update the package by providing its own, and the fix the bug.  I could experiment with submitting an update to Alpine Linux (i.e. upstream) first and see how receptive they are.  I would leave this ticket open until it is resolved to make other users aware of this discovery.

**Comment by pgj** [comment]
@ish-org I have checked the home page of WPA Supplicant and the latest release is 2.10.  I could not find any further minor version, such as 2.10.7 as you suggested in your earlier comment.  You actually wrote `wap_supplicant` but I guess you meant `wpa_supplicant`.  Nevertheless I believe you that the fix for the named bug has been published but I would like to ask for your help in extracting the related patch from the `wpa_supplicant` git repository to ship that with Wifibox.

**Comment by pgj** [comment]
@ish-org for your information, I have pushed an [update to `wifibox-alpine`](https://github.com/pgj/freebsd-wifibox-port/commit/7ee8636b09ab7c221210afd9647fe49336dcf951) where the `wpa_supplicant` build configuration has been changed.  I am not sure if this helps with your problem, but it may be worth a try.

**Comment by pgj** [comment]
@ish-org could you please answer?

**Comment by ish-org** [comment]
Thank you and sorry to late repry.
Unfortunately, this is not work for SSL3.
To enable SSL3, wpa_supplicant must link libssl1.1 and libcrypto1.1.
wpa_supplicant-2.10-r2.apk dosen't use them.

P.S. wpa_supplicant-2.10-r2 seems to handle WPA-EAP-SUITE-B and WPA-EAP-SUITE-B-192.  This is necessary to use WPA3-enterprise but I cannot connect with WPA3-enterprise.  My setting may be wrong.

**Comment by pgj** [comment]
@ish-org could you please elaborate on your comment about the WPA Supplicant upstream fix for your problem?  I would like to include this in the Wifibox Alpine image, but I do not know where to find it.

**Comment by ish-org** [comment]
I'm not an expert either, but I think the following information will be helpful.
https://bbs.archlinux.org/viewtopic.php?id=281039
https://bugs.launchpad.net/ubuntu/+source/wpa/+bug/1958267

**Comment by pgj** [comment]
Many thanks for the hint, that is what I exactly needed!  I created an updated version (`r3`) of the `wpa_supplicant` 2.10 package that you can try with [the `20230326` version of `wifibox-alpine`](https://github.com/pgj/freebsd-wifibox-port/tree/144b524b70adca0c5345cbf9227e0aefb3997b10).

**Comment by ish-org** [comment]
Thank you very much.
As I'm very busy now and I'll try later.

**Comment by ish-org** [comment]
Great!
wifibox-alpine-20230326 works fine with SSL3.

P.S.
It still can't be connected with the WPA3-enterprise 192bit-security.
The following is my wap_supplicant.conf.

network={
  ssid="XXXXX"
  proto=RSN
  key_mgmt=WPA-EAP-SUITE-B-192
  pairwise=GCMP-256
  group_mgmt=BIP-GMAC-256
  pairwise=GCMP-256
  group=GCMP-256
  group_mgmt=BIP-GMAC-256
  eap=TLS
  identity="xxx"
  ca_cert="/etc/wpa_supplicant/cacert.pem"
  private_key="/etc/wpa_supplicant/bundle.p12"
  private_key_passwd="xxxxxxxxx"
  openssl_ciphers="SUITEB192"
  ieee80211w=2
}

wifibox:~# wpa_supplicant -Dnl80211 -iwlan0 -c/etc/wpa_supplicant/wpa_supplicant.conf
Successfully initialized wpa_supplicant
wlan0: CTRL-EVENT-REGDOM-CHANGE init=DRIVER type=WORLD
wlan0: SME: Trying to authenticate with xx:xx:xx:xx:xx:xx (SSID='XXXXXXXXX' freq=5260 MHz)
wlan0: CTRL-EVENT-REGDOM-CHANGE init=DRIVER type=COUNTRY alpha2=JP
wlan0: Trying to associate with xx:xx:xx:xx:xx:xx (SSID='XXXXXXXXX' freq=5260 MHz)
wlan0: Associated with xx:xx:xx:xx:xx:xx
wlan0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
wlan0: CTRL-EVENT-EAP-STARTED EAP authentication started
wlan0: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=4 -> NAK
wlan0: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=13
wlan0: CTRL-EVENT-EAP-METHOD EAP vendor 0 method 13 (TLS) selected
wlan0: CTRL-EVENT-EAP-FAILURE EAP authentication failed
wlan0: CTRL-EVENT-DISCONNECTED bssid=xx:xx:xx:xx:xx:xx reason=23
wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="XXXXXXXXX"  auth_failures=1 duration=10 reason=AUTH_FAILED
BSSID xx:xx:xx:xx:xx:xx ignore list count incremented to 2, ignoring for 10 seconds

Perhaps,  I missed to enable SUITEB192 cipher of openssl, but I don't know the right way.

**Comment by ish-org** [comment]
It seems that it can't connect by wpa3-enterprise due to incorrect settings in wpa_supplicant.conf. On ubuntu, although I can connect by wpa3-enterprise with nmcli settings, after 'systemctl mask wpa_supplicant' and reboot to don't use nmcli setting, I can't connect with this wpa_supplicant, the same error occured. Can somebody tell me the right settings in wpa_supplicant.conf ?

**Comment by ish-org** [comment]
Finally, I can connect via wpa3-enterprise on wifibox-alpine-iwlwifi-20230326 by removing 'openssl_ciphers="SUITEB192"' from wpa_supplicant.conf.
Sorry to worry about you.

**Comment by pgj** [comment]
No problem.  Thanks for the confirmation!  That said, I am closing this ticket.
